[package]
name = "ReShade_Linux_Install"
version = "0.1.0"
edition = "2021"

[dependencies]
zip-extract = "0.1.1"
fs_extra = "1.2.0"
walkdir = "2"
goblin = "0.5.4"
gtk = "0.15.5" 
quale = "1.0.0"
which = "4.3.0"
rust-ini = "0.18.0"